### ISSUE TITLE
Can you change the style, colors, font size and font name?

### ISSUE THREAD

**Issue by rudolfschmidt** [huijunchen9260/dmenufm#11]

**Comment by huijunchen9260** [comment]
You can change font size and font name (See troubleshooting)
May I ask what do you mean by style and colors? Does the colors means the different level of dmenufm have different color? And what kind of style you wish could customize?

**Comment by huijunchen9260** [comment]
https://github.com/huijunchen9260/dmenufm#dmenu-font-is-too-bigsmall

Adjust font size by "FONTNAME-FONTSIZE"

**Comment by huijunchen9260** [comment]
Solved by https://github.com/huijunchen9260/dmenufm#i-want-to-configure-the-color-and-font-of-dmenufm
