### ISSUE TITLE
Do me a flavour, please...

### ISSUE THREAD

**Issue by terminalforlife** [huijunchen9260/dmenufm#22]
Can you run `uname -s` on your Mac rig? I need to see what is typically displayed. Your OSTYPE check needs addressing, as I believe it's not defined by POSIX, and is probably not best relied upon anyway. However, I'm lead to believe that `uname` is commonplace.

Can you also run: `cat /proc/version` (another method, which I've never been able to try on Mac)

**Comment by huijunchen9260** [comment]
I am using Arch, not macXD
I got that chunk of code from fff:

https://github.com/dylanaraps/fff/blob/master/fff#L5

**Comment by terminalforlife** [comment]
Lol I love that 'fff' name.

In that case, hopefully somebody else with a Mac can help with this.

**Comment by VebbNix** [comment]
Had my buddy who has a Mac get this output for you, so here you go
```
Darrens-MacBook-Pro:~ nothing$ uname -s
Darwin
Darrens-MacBook-Pro:~ nothing$ cat /proc/version
cat: /proc/version: No such file or directory
```
So, as you can see /proc/version doesn't exist (There probably is some other similar file you could use, but this one isn't here.) and uname -s is 'Darwin'

**Comment by terminalforlife** [comment]
Thanks! That's gonna help a lot.

**Comment by huijunchen9260** [comment]
> Had my buddy who has a Mac get this output for you, so here you go
> 
> ```
> Darrens-MacBook-Pro:~ nothing$ uname -s
> Darwin
> Darrens-MacBook-Pro:~ nothing$ cat /proc/version
> cat: /proc/version: No such file or directory
> ```
> 
> So, as you can see /proc/version doesn't exist (There probably is some other similar file you could use, but this one isn't here.) and uname -s is 'Darwin'

So it means that I can only use Darwin and we can apply it to macos?

**Comment by terminalforlife** [comment]
Yeah, but don't count on it too much, in-case different versions of MacOS have different output. Hopefully it's always Darwin.
