### ISSUE TITLE
dmenufm breaks after patching

### ISSUE THREAD

**Issue by Dev380** [huijunchen9260/dmenufm#39]
Hello, I've been using dmenufm for a while and it worked fine. I patched dmenu to add fuzzy highlighting, line height, solarized theme, etc. and it still worked. But then I added the case-insensitive patch, dmenu works as expected but dmenufm says 
```No program selected, falling back to dmenu.
usage: dmenu [-bfiv] [-l lines] [-h height] [-p prompt] [-fn font] [-m monitor]
             [-nb color] [-nf color] [-sb color] [-sf color]
             [-nhb color] [-nhf color] [-shb color] [-shf color] [-w windowid]
```
I ran dmenufm -m rofi and it works.
I ran dmenufm -m dmenu and this is the output:
```
Program `dmenu` not recognized, trying to run without any option. If this does not work, please set both \'\' and \'\' variable!
usage: dmenu [-bfiv] [-l lines] [-h height] [-p prompt] [-fn font] [-m monitor]
             [-nb color] [-nf color] [-sb color] [-sf color]
             [-nhb color] [-nhf color] [-shb color] [-shf color] [-w windowid]
```
dmenu is in my path and running ls | dmenu and dmenu_run both works. They are in $HOME/.local/bin

**Comment by huijunchen9260** [comment]
Please put the following configuration in your `dmenufm.conf` and tell me whether it fixed:

```conf
FM_OPTS=''
FM_OPTS_GENERIC=""
FM_OPTS_ACTION_LV1=""
FM_OPTS_ACTION_LV2=""
FM_OPTS_ACTION_BULK=""
FM_OPT_PROMPT=''-p"
```

**Comment by Dev380** [comment]
I added this instead since the quotes don't line up:
```
FM_OPTS=''
FM_OPTS_GENERIC=""
FM_OPTS_ACTION_LV1=""
FM_OPTS_ACTION_LV2=""
FM_OPTS_ACTION_BULK=""
FM_OPT_PROMPT="-p"
```
Now it works, but it doesn't have the default look, it functions but looks like regular dmenu, do you know how to restore the default skin?

**Comment by huijunchen9260** [comment]
Oh I mistyped in PROMPT stuff.

It doesn't, because these options are deactivated in order to test the problem. 
I conjecture that your patching might change some behavior of dmenu, which changes the default configuration of the dmenufm. I guess once you explicitly set those `FM_OPT` stuff, you can probably avoid the patching problem.
If you still have problems, please open an issue. 

Now you can add the `FM_OPTS` that you want. For example, the default behavior may look like:

```conf
FM_OPTS="-f -i -l 10"
FM_NOTIF_OPTS="-fn "$FM_NOTIF_FONT" -sb "#d79921" -sf "#1d2021" -nf "#000000" -nb "#000000""
FM_DANGER_OPTS="-fn $FM_DANGER_FONT -nb darkred -sb red -sf white -nf gray"
```
Tweak these options to you like.

**Comment by Dev380** [comment]
Thanks for answeing, I found out that the problem is -i is unsupported since the case insensitive patch changes that flag.
