### ISSUE TITLE
Miss leading install instraction.

### ISSUE THREAD

**Issue by musicfunfan** [huijunchen9260/dmenufm#42]
So on the install section of the readme you say that we need to cd to Makefile directory but there is not such directory this is a file... With this name... 
So we need to fix that i thing... Or am i missing something here ? This is possible too.

**Comment by huijunchen9260** [comment]
Maybe I should type something like `cd` to the directory where `Makefile` is located.

You can install it with the following shell command:

```shell
git clone https://github.com/huijunchen9260/dmenufm
cd dmenufm
sudo make install
```

Hope this is helpful.
